### PR TITLE
Specifications for converting model export CSV files to PMML

### PR DESCRIPTION
**Pull request by yulric**
1. The spec document is in assets/specs/model-csv-to-pmml/model-csv-to-pmml-spec.Rmd
2. All files in the flow-chart folder are XML files that describe the flow charts used in the spec
3. All files in the images folder are images used in the spec
4. All files in the test-files folder have input and output combinations used for the testthat tests described in this PR

### CODE REVIEW

**Review by DarkShadeKnigh — APPROVED** [review]

**Review by DougManuel — APPROVED** [review]
I am not quite finished with review but giving an approval. I may add comments later today.

My main comments are for @DarkShadeKnigh and next steps. 
- Could we make the implementation nice and modular?
- Keep in mind, we will need additional transformations. It would be nice to be able to eventually work for tidymodels or other approaches or libraries. 

I was thinking something along the lines of:
make_center_pmml <- function(origVaraiable, centreValue, centeredVariable, centreredVariableType) {

}

return is an XML snippet.

Then have our implementation using CSV files wrapped around.

**Review by DougManuel — APPROVED** [review]
I've reviewed the remaining document. Looks all good -- actually great. Super helpful to have the expected return which can be used for testing.

Re: my previous comment about modular approach. @DarkShadeKnigh could add his proposed function calls to this document. It would build on the business logic stage.

**Comment by DarkShadeKnigh** [comment]
Basic UML added at "assets\specs\model-csv-to-pmml\flow-charts\suggested_implementation.drawio"
@yulric @DougManuel

**Comment by DougManuel** [comment]
@DarkShadeKnigh Are you thinking that covert_to_pmml would have convert all files, or would that function access a series of functions such as covert_rcs_to_pmml?

**Comment by DarkShadeKnigh** [comment]
> @DarkShadeKnigh Are you thinking that covert_to_pmml would have convert all files, or would that function access a series of functions such as covert_rcs_to_pmml?

I was thinking of having a switch case inside the function that uses the fileType as its condition. But yes the convert_to_pmml would handle all files

**Comment by yulric** [comment]
@DarkShadeKnigh Can you do what we decided some time ago with new functions? Go in add comments for what you will do, to act as a skeleton for your function. Also add any internal functions you think the main function will need and add comments for that too.

**Comment by DarkShadeKnigh** [comment]
@yulric the requested skeleton was added at R/model_to_pmml.R

**Comment by yulric** [comment]
@DarkShadeKnigh I'm not sure I understand why you need recursion for this? I was thinking a simple iterator would work for this implementation where you go through each row of the model export and model steps files and fill in the converted PMML for each row?

Also, can you add the skeletons for each function that converts a specific row into PMML. Keep in mind that a lot of functions, especially the step functions will be resued for example with broom. They should be generic enough to account for this, a recommendation would be to use the column names as parameters into these functions.

Final thing, I'd recommend against writing code since this exercise is about making sure you approach to this problem makes sense from a very level. Comments should be more than enough and they can be formatted as steps.

**Comment by DarkShadeKnigh** [comment]
Closing in order to delete the branch

**Pull request closed without merging**
