### PR TITLE
add role

### PR DESCRIPTION
**Pull request by DougManuel**
The proposal to add `role` to bllflow.

### CODE REVIEW

**Comment by CBjerke** [comment]
@DougManuel I've made a couple of edits to "ROLE". Additionally, I wasn't sure what "Suggested can be named anything and be used or reused for any purpose" meant.

**Comment by DarkShadeKnigh** [comment]
Looks good to me my only concern is the multiple roles on one variable in case something is labeled as an intermediate variable and an outcome. So might have to come up with list of conflicting roles

**Comment by DougManuel** [comment]
I'll clarify.

> Made a couple of edits. However, wasn't sure what "Suggested can be named anything and be used or reused for any purpose" meant.

That was pasted from Recipes description of roles. https://github.com/tidymodels/recipes/blob/master/vignettes/Roles.Rmd#L22

**Comment by DougManuel** [comment]
@DarkShadeKnigh Are we using CI for only master, or dev and other branches.

**Comment by DougManuel** [comment]
> @DougManuel, I think the way it is currently written implies that a role (e.g., ‘predictor’) can be used for multiple purposes as opposed to the ability to define a role for each unique purpose…but I may be off-mark? 

@CBjerke Yes. `recipes` allows multiple roles and I think we should too. So, you could have the roles, 'predictor', 'table-1', etc. 

@DarkShadeKnigh is right that roles could conflict. Should be a predictor and outcome. I'm personally not too fussed. That is really up to the user to keep in order, but we could implement additional rules (later) if we want. Note that this issue could happen with the current role implementation in `reciipe`.

**Comment by DarkShadeKnigh** [comment]
> @DarkShadeKnigh Are we using CI for only master, or dev and other branches.

Its used on all branches but deployment to gh-pages is only done from master branch

**Pull request merged**
